name: Release Drafter

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
